AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**
    - config/unicorn.rb
  DisplayCopNames: true

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
   '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails
